/**
 * Code Intelligence — shared types
 *
 * CodeContext is the output of the Code Intelligence layer.
 * It carries structural information about code relevant to a request,
 * derived from a code graph (e.g. generated by Graphify).
 *
 * Consumers: Issue Agent, future Engineering Agent.
 * Producers: CodeIntelligenceService via a CodeGraphProvider.
 */

import type { TriageResult } from '../db/schema.js';
import type { TriageInput } from '../triage/port.js';

// ── Input ────────────────────────────────────────────────────────────────────

/** Input to the Code Intelligence layer, composed from existing contracts. */
export interface CodeIntelligenceInput {
  input:         TriageInput;
  triageResult:  TriageResult;
  /** Absolute or relative path to the repository root to analyse. Optional. */
  repositoryPath?: string;
}

// ── Output ───────────────────────────────────────────────────────────────────

/**
 * Status of the code analysis attempt.
 *   accessible  — graph was available and relevant context was found
 *   no_match    — graph was available but no relevant symbols found
 *   inaccessible — repository path not provided or not reachable
 *   error       — graph provider failed (CLI missing, extract failed, etc.)
 */
export type CodeAccessStatus = 'accessible' | 'no_match' | 'inaccessible' | 'error';

/** A directed relation between two code symbols. */
export interface CodeRelation {
  from:  string;
  to:    string;
  kind:  string;
}

/**
 * Compact code context returned to consumers.
 * Budgets are enforced by CodeIntelligenceService:
 *   relevantSymbols   — max 10
 *   relevantFiles     — max 5
 *   callPaths         — max 3
 *   potentiallyImpacted — max 10
 */
export interface CodeContext {
  requestId:            string;
  status:               CodeAccessStatus;
  repository:           string | null;
  ref:                  string | null;
  relevantSymbols:      string[];
  relevantFiles:        string[];
  relations:            CodeRelation[];
  callPaths:            string[];
  potentiallyImpacted:  string[];
  summary:              string;
  evidence:             string[];
  provider:             string;
}

// ── Provider interface ───────────────────────────────────────────────────────

/**
 * Abstraction over any code-graph backend (Graphify, mock, future MCP, …).
 * Implementations must never throw — return an error CodeContext instead.
 */
export interface CodeGraphProvider {
  readonly name: string;
  getContext(input: CodeIntelligenceInput): Promise<CodeContext>;
}
